### ISSUE TITLE
Zoek en filter functie - Toegankelijkheid

### ISSUE THREAD

**Issue by Tristandemuijnck** [Tristandemuijnck/lets-jam-webapplicatie#12]

**Comment by Demivdm** [comment]
Tab order is weer correct. Verder voor toegankelijkheid een achtergrond kleur toegevoegd aan de  actieve tag. 
https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/0005249e38b86d0acc4c7271fe00bd2740d6390b
