### ISSUE TITLE
Overzicht werkvormen - Te weinig margin op de container 

### ISSUE THREAD

**Issue by Siem-P** [Tristandemuijnck/lets-jam-webapplicatie#49]
Na het uploaden van een nieuwe werkvorm. Lopen de twee werkvormen op een nieuwe regel door de footer.
Hierdoor kan je niet naar de desbetreffende detail pagina.

<img width="831" alt="Screenshot 2024-01-12 at 10 10 16" src="https://github.com/Tristandemuijnck/lets-jam-webapplicatie/assets/64197688/4b552469-39fd-4ba6-9a56-e2fe41877a33">

**Comment by Tristandemuijnck** [comment]
Fixed: https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/f823dd737ca49762dd0a4aede7410b0b9f84544f
