### ISSUE TITLE
Upload werkvorm functie - Studiejaar input field

### ISSUE THREAD

**Issue by Siem-P** [Tristandemuijnck/lets-jam-webapplicatie#50]
Tijdens het invullen van het werkvorm formulier krijg je de optie om het studiejaar in te vullen. Volgens mij moet het leerjaar zijn volgens de functionaliteit.

Daarnaast moet er een 'minmax' op het input veld om onrealistische antwoorden te voorkomen.

<img width="452" alt="Screenshot 2024-01-12 at 10 12 43" src="https://github.com/Tristandemuijnck/lets-jam-webapplicatie/assets/64197688/c476dd32-a795-4c30-bc67-9f1b88990aa6">

**Comment by Tristandemuijnck** [comment]
Dit inputveld is verwijderd, omdat deze geen table row heeft in de CMD database. De data was dus overbodig.

Removed: https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/f23a5eb9d173b28bdef46029bfac51475f95279c
