### ISSUE TITLE
Upload werkvorm functie - Video input field

### ISSUE THREAD

**Issue by Siem-P** [Tristandemuijnck/lets-jam-webapplicatie#51]
Het is mogelijk om verschillende formats up loaden in het video input veld. Ik denk dat dit alleen video formats horen te zijn.

<img width="462" alt="Screenshot 2024-01-12 at 10 15 24" src="https://github.com/Tristandemuijnck/lets-jam-webapplicatie/assets/64197688/9aa22962-4912-4661-9976-2136786dd06f">

**Comment by Tristandemuijnck** [comment]
Fixed: https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/177130c8151e6be6b192c8e13680491ea4984ee8
