### ISSUE TITLE
Focus state veranderen in javascript functie

### ISSUE THREAD

**Issue by RalphKocken** [Tristandemuijnck/lets-jam-webapplicatie#52]
https://github.com/Tristandemuijnck/lets-jam-webapplicatie/blob/2cf0e848c877786cad5dc734acac9e477b96b381/src/lib/atoms/NavFilterList.svelte#L120

Hoi Deem,

Wij hadden het even over het focussen van de tags. Misschien kan je mijn voorbeeld gebruiken voor jou functie. 
https://github.com/Sascha-davidson/lets-jam-webapplicatie/blob/a714107cf482e8c77fa7b12917162809a3277b38/src/routes/statskeeper/%2Bpage.svelte#L4

Op regel 4 staat de variabele die je met elke click veranderd. 
Op regel 6 staat de functie die de meegegeven parameter als de variabele (regel 4) zet.
Op regel 69 staat een button die de functie uitvoert.

**Comment by Demivdm** [comment]
Hee Ralph, Hier heb ik de achtergrond voor de actieve tag toegevoegd. ik heb de functie toegevoegd in de volgende commit; https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/43b5f0ef045115596a1fc3f05a579d22b9dd618a
