### ISSUE TITLE
Flex-wrap gebruiken op je nav-list

### ISSUE THREAD

**Issue by RalphKocken** [Tristandemuijnck/lets-jam-webapplicatie#54]
https://github.com/Tristandemuijnck/lets-jam-webapplicatie/blob/2cf0e848c877786cad5dc734acac9e477b96b381/src/lib/atoms/NavFilterList.svelte#L87C3-L87C3

Kijk even naar de tag-list, misschien kan je flex-wrap gebruiken om het beter responsive te maken. Op grote schermen wordt de lijst prima weergegeven maar wanneer je het scherm kleiner maakt valt de lijst weg.

**Comment by Demivdm** [comment]
Thanks! Ik heb het gefixt op regel https://github.com/Tristandemuijnck/lets-jam-webapplicatie/blob/4365646af8a50e569a1bf49fdd958720af415ae8/src/lib/atoms/NavFilterList.svelte#L169
