### ISSUE TITLE
Waarom wordt er row-reverse gebruikt?

### ISSUE THREAD

**Issue by RalphKocken** [Tristandemuijnck/lets-jam-webapplicatie#55]
https://github.com/Tristandemuijnck/lets-jam-webapplicatie/blob/2cf0e848c877786cad5dc734acac9e477b96b381/src/lib/atoms/NavFilterList.svelte#L169

De tab-order klopt niet door het gebruiken van row-reverse. De zoekknop wordt nu eerder gefocust dan het input veld. 
In de HTML kan je het input veld boven de submit button zetten.

**Comment by Demivdm** [comment]
Thanks voor de feedback! Ik heb het probleem opgelost in commit: https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/cea08437724467fabf2ac4869ed8869502e7aa08
