### ISSUE TITLE
Filter functie

### ISSUE THREAD

**Issue by Tristandemuijnck** [Tristandemuijnck/lets-jam-webapplicatie#6]
# Wat moet er nog gebeuren om het af te maken
## Is het component responsive en voldoet het aan de huisstijl?
 
- [x] Voor responsive moet er nog wat gebeuren. Nog niet op alle apparaten getest
- [x] Kan nog een breakpoint worden toegevoegd voor M-scherm
- [ ] Small screen doet het
 
## Voldoet het component aan de coding standards?
 
- [x] Gebruik gemaakt van Sveltekit
- [x] HTML semantisch geschreven
- [x] CSS classes gebruikt gemaakt van kebab-casing & id's van Camelcasing
- [ ] CSS properties op alfabetische volgorde gezet
- [ ] Javascript variabelen imports, definiëren, eventListeners en functies gegroepeerd  
- [ ] Prettier css ordering 
- [ ] Tabbing spacing op 4 spaces
- [x] Consistent gebruik van semi-colons
- [x] Comments bij code: 
* Functies: beschrijf in een regel wat de functie doet. 
* Components : Beschijf in de html per component wat het inhoud, kort & bondig.
 
## Is het component toegankelijk?
 
- [ ] Focus test gedaan
- [ ] Nog geen handmatige tests gedaan
- [x] Light house
 
## Is het component performant?
 
- [ ] Alle afbeeldingen moeten nog worden toegevoegd en geoptimaliseerd
- [ ] Image sizes staan in de HTML in de template
- [ ] Loading="lazy" staat in de HTML
- [ ] Afbeeldingen hebben een vaste `width` & `height`

## Scenario's

- [x] Als gebruiker wil ik specifieke tags kunnen selecteren en toepassen als filters, zodat ik gericht kan zoeken naar werkvormen die aan mijn interesses voldoen.
- [x] Als gebruiker wil ik een duidelijke weergave van beschikbare filteropties, zodat ik snel en gemakkelijk kan beslissen welke tags ik wil toepassen.
- [ ] Als gebruiker wil ik een overzichtelijke weergave van de geselecteerde filters zien, zodat ik altijd weet welke criteria op dat moment van toepassing zijn.

**Comment by Demivdm** [comment]
Alle comments verwijderd, filter werkt en is toegevoegd.
https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/46cba33b7068f278360800c2be7b2ffe6cb9cd03
