### ISSUE TITLE
Upload werkvorm functie

### ISSUE THREAD

**Issue by Stefan-Espant** [Tristandemuijnck/lets-jam-webapplicatie#7]
# Wat moet er nog gebeuren om het af te maken
## Is het component responsive en voldoet het aan de huisstijl?
 
- [x] Het component is responsive op verschillende schermgroottes
 
## Voldoet het component aan de coding standards?
 
- [x] Gebruik gemaakt van Sveltekit
- [x] HTML semantisch geschreven
- [x] CSS classes gebruikt gemaakt van kebab-casing & id's van camelCasing
- [x] CSS properties op alfabetische volgorde gezet
- [x] Javascript variabelen imports, definiëren, eventListeners en functies gegroepeerd  
- [ ] Prettier css ordering 
- [x] Tabbing spacing op 4 spaces
- [x] Consistent gebruik van semi-colons
- [x] Comments bij code: 
* Functies: beschrijf in een regel wat de functie doet. 
* Components : Beschijf in de html per component wat het inhoud, kort & bondig.
 
## Is het component toegankelijk?
 
- [x] Focus test gedaan
- [x] Light house
 
## Is het component performant?
 
- [x] Het component is performant

**Comment by Tristandemuijnck** [comment]
# User test
## Scenario's

- [ ] Als gebruiker kan ik een nieuwe werkvorm uploaden.
- [ ] Als gebruiker kan ik een nieuwe werkvorm uploaden, **zonder** een video mee te sturen.

**Comment by Siem-P** [comment]
# User Test - Siem
- [] Als gebruiker kan ik een nieuwe werkvorm uploaden.
- [ ]  Als gebruiker kan ik een nieuwe werkvorm uploaden, zonder een video mee te sturen.
- [ ]  Als gebruiker kan ik het formulier binnen Safari gebruiken.
- [ ]  Als gebruiker kan ik het formulier binnen Firefox gebruiken
- [ ]  Als gebruiker kan ik het formulier binnen Chrome gebruiken

Daarnaast zijn de bovenstaande checkboxes aangekruisd die voldaan zijn.

**Comment by Tristandemuijnck** [comment]
Added: https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/2cf0e848c877786cad5dc734acac9e477b96b381
Added: https://github.com/Tristandemuijnck/lets-jam-webapplicatie/commit/df8d94100f24ed49e4e13b811aa5dd2fbf082b9c
